Update trigger.v2.yml 2

diff --git a/.github/workflows/trigger.v2.yml b/.github/workflows/trigger.v2.yml
--- a/.github/workflows/trigger.v2.yml
+++ b/.github/workflows/trigger.v2.yml
@@ -8,7 +8,7 @@ on:
         required: true
         type: choice
         options:
-          - deploy-dev
+          - dev-deploy
           - next
           - main
 
@@ -27,7 +27,7 @@ jobs:
         id: set-target-branch
         run: |
           case "${{ github.event.inputs.from-branch }}" in
-            deploy-dev)
+            dev-deploy)
               echo "target-branch=master" >> $GITHUB_ENV
               ;;
             next)
@@ -47,12 +47,19 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          git fetch origin
-          git checkout ${{ env.target-branch }}
-          git pull origin ${{ env.target-branch }}
-          git fetch origin ${{ github.event.inputs.from-branch }}:${{ github.event.inputs.from-branch }}
-          git rebase ${{ github.event.inputs.from-branch }} 
-          git push --force origin ${{ env.target-branch }}
+            git config --global user.email "rjimenez@nogin.com"
+            git config --global user.name "RoyJimenezValdez"
+            git fetch origin
+            git checkout ${{ env.target-branch }}
+            git pull origin ${{ env.target-branch }}
+            git fetch origin ${{ github.event.inputs.from-branch }}:${{ github.event.inputs.from-branch }}
+            git rebase ${{ github.event.inputs.from-branch }} || (
+                echo "Rebase failed. Resolving conflicts automatically." &&
+                git rebase --abort &&
+                git merge --strategy=recursive -X theirs ${{ github.event.inputs.from-branch }} --allow-unrelated-histories
+            )
+
+            git push --force origin ${{ env.target-branch }}
 
       # Notify the action is complete
       - name: Complete
